// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ-FPXmaz3hQBVNj6SSmWtD56fQAibvG8',
    appId: '1:450979541015:web:0e9916c75c76fe259bec52',
    messagingSenderId: '450979541015',
    projectId: 'notiftest-9b93c',
    authDomain: 'notiftest-9b93c.firebaseapp.com',
    storageBucket: 'notiftest-9b93c.firebasestorage.app',
    measurementId: 'G-PNZPXLYWYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3QoRXGfam_OHIoPfn8ETonskmq2LJMjI',
    appId: '1:450979541015:android:679f9601e8f05f8a9bec52',
    messagingSenderId: '450979541015',
    projectId: 'notiftest-9b93c',
    storageBucket: 'notiftest-9b93c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI83zjRyz0MeTZ2BYPvsQcwOyUoWBQH1I',
    appId: '1:450979541015:ios:c17f0915bb215db99bec52',
    messagingSenderId: '450979541015',
    projectId: 'notiftest-9b93c',
    storageBucket: 'notiftest-9b93c.firebasestorage.app',
    iosBundleId: 'com.firebase.firebaseDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI83zjRyz0MeTZ2BYPvsQcwOyUoWBQH1I',
    appId: '1:450979541015:ios:c17f0915bb215db99bec52',
    messagingSenderId: '450979541015',
    projectId: 'notiftest-9b93c',
    storageBucket: 'notiftest-9b93c.firebasestorage.app',
    iosBundleId: 'com.firebase.firebaseDb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ-FPXmaz3hQBVNj6SSmWtD56fQAibvG8',
    appId: '1:450979541015:web:6a3c4fc62fbe5cef9bec52',
    messagingSenderId: '450979541015',
    projectId: 'notiftest-9b93c',
    authDomain: 'notiftest-9b93c.firebaseapp.com',
    storageBucket: 'notiftest-9b93c.firebasestorage.app',
    measurementId: 'G-TM9G5XR8VY',
  );
}
